what's the secret num?!?!
mjjsalcedo/Secret-Number-Generator pull request #1
Opened 2017-06-15 23:42 UTC by mjjsalcedo

2017-06-15 23:48 UTC, taesup requested changes

2017-06-15 23:48 UTC, taesup commented on secret_number.js
> +    let generatedNumber = (Math.random()*1000000);
So this will give you all the numbers from 0 - 999999 but not 1000000. Can you think of a Math method that'll make this go to 1000000

Also this declaration should be a const. But this is also acceptable.

2017-06-16 00:05 UTC, mjjsalcedo commented on secret_number.js
> +    let generatedNumber = (Math.random()*1000000);
Okay! I made an edit, can you please let me know if it's okay? Thank you!

2017-06-16 00:09 UTC, taesup requested changes

2017-06-16 00:09 UTC, taesup commented on secret_number.js
> +    let generatedNumber = (Math.random()*1000001);
You're close! But at the max value you'll still end up with 1000000.99999 which is just a bit too large. Can you think of a Math function that could bring this down to just 1000000?

2017-06-16 00:30 UTC, taesup commented
Looks Good! Feel free to merge with master.

![YES](https://github.com/jglovier/gifs/blob/gh-pages/high-five/high-five-met-your-mother.gif?raw=true)

2017-06-16 00:34 UTC, mjjsalcedo commented
ty!!!!!!!

2017-06-16 00:34 UTC, merged